apiVersion: v1
kind: Secret
metadata:
  name: perf-secret
  namespace: perf-test
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "perf_a"
  SPRING_DATASOURCE_PASSWORD: "1234567890"

  DATABASE_USERNAME: "perf_a"
  DATABASE_PASSWORD: "1234567890"

  SPRING_R2DBC_USERNAME: "perf_a"
  SPRING_R2DBC_PASSWORD: "1234567890"

  QUARKUS_DATASOURCE_USERNAME: "perf_a"
  QUARKUS_DATASOURCE_PASSWORD: "1234567890"

  QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_USER: "perf_a"
  QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_PASSWORD: "1234567890"

  DATABASE_USER: "perf_a"
  KTOR_DATABASE_USER: "perf_a"
  KTOR_DATABASE_PASSWORD: "1234567890"
