---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-reactive-perf-jvm
  namespace: perf-test
  labels:
    app: quarkus-reactive-perf-jvm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: quarkus-reactive-perf-jvm