apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-perf-native-micro
  namespace: perf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-perf-native-micro
  template:
    metadata:
      labels:
        app: quarkus-perf-native-micro
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
    spec:
      containers:
        - name: quarkus-perf-native-micro
          image: ghcr.io/matejsaric32/quarkus-perf-native-micro:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: quarkus-perf-config
            - secretRef:
                name: perf-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3