apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-perf
  namespace: perf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-perf
  template:
    metadata:
      labels:
        app: ktor-perf
    spec:
      containers:
        - name: ktor-perf
          image: ghcr.io/matejsaric32/ktor-perf:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ["java", "-jar", "app.jar", "-config=/app/application.yaml"]
          volumeMounts:
            - name: config
              mountPath: /app/application.yaml
              subPath: application.yaml
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: ktor-perf-config