---
apiVersion: v1
kind: Service
metadata:
  name: spring-reactor-perf
  namespace: perf-test
  labels:
    app: spring-reactor-perf
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spring-reactor-perf
